### ISSUE TITLE
photo of the day no longer working

### ISSUE THREAD

**Issue by lucamp** [sal0max/muzei-nationalgeographic#9]
Hi,
photo of the day is no longer working.
The issue happened suddently without apps update or modification. It could be that national geographic changed something again in their site.

Random photo works, but I do not know which range of dates is working

Thanks
Luca

muzei 3.0.2 (fdroid)
national geographic for muzei 2.1.1 (fdroid)
android LineageOS 7.1.2

**Comment by sal0max** [comment]
Thanks for the notice.

There seemed to have happened some smaller API changes, which I addressed in 8021d9f0b2196874c24288ef0f8e62a37b8dff1e.

However the bigger issue is, since the shutdown of the [Your Shot Community](https://petapixel.com/2019/09/03/disney-shutting-down-natgeo-your-shot-website-to-focus-on-instagram/), photos of the day appear only very sporadic, from time to time.

Check out the website: https://www.nationalgeographic.com/photography/photo-of-the-day/archive/
Missing photos are e.g. 2019-12-08, 2019-12-07, 2019-12-01, 2019-11-24, 2019-11-23, 2019-11-17, 2019-11-16, and so on.

Nothing I can do about that.
